
CREATE DATABASE MantenimientoInformatico;

USE MantenimientoInformatico;

CREATE TABLE `CLIENTE` (
  `CI` char(8) NOT NULL,
  `TIPO_PERFIL` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`CI`),
  CONSTRAINT `CLIENTE_FK` FOREIGN KEY (`CI`) REFERENCES `PERSONA` (`CI`)
)



CREATE TABLE `HARDWARE` (
  `N°_INUSMO` int(11) NOT NULL,
  PRIMARY KEY (`N°_INUSMO`),
  CONSTRAINT `HARDWARE_FK` FOREIGN KEY (`N°_INUSMO`) REFERENCES `INSUMO` (`N°_INSUMO`)
) 



CREATE TABLE `INSUMO` (
  `N°_INSUMO` int(11) NOT NULL,
  `NOMBRE_INSUMO` varchar(20) DEFAULT NULL,
  `CANTIDAD_STOCK` int(11) DEFAULT NULL,
  `DESCRIPCION` varchar(100) DEFAULT NULL,
  `PRECIO` float DEFAULT NULL,
  PRIMARY KEY (`N°_INSUMO`)
)



CREATE TABLE `PAQUETE` (
  `ID_PAQUETE` int(11) NOT NULL,
  `NOMBRE_PAQUETE` varchar(30) DEFAULT NULL,
  `CALCULO_DE_HORAS` float DEFAULT NULL,
  `COSTO_PRESUPUESTADO` float DEFAULT NULL,
  PRIMARY KEY (`ID_PAQUETE`)
) 



CREATE TABLE `PERFIL` (
  `ID_PERFIL` int(11) NOT NULL,
  `NOMBRE_PERFIL` varchar(15) DEFAULT NULL,
  `DESCUENTO` float DEFAULT NULL,
  PRIMARY KEY (`ID_PERFIL`)
) 



CREATE TABLE `PERSONA` (
  `CI` char(8) NOT NULL,
  `Nombre` varchar(30) NOT NULL,
  `Apellido_Paterno` varchar(30) NOT NULL,
  `Apellido_Materno` varchar(30) NOT NULL,
  `Calle` varchar(30) DEFAULT NULL,
  `Numero` char(15) DEFAULT NULL,
  `Localidad` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`CI`)
) 



CREATE TABLE `PROVEEDOR` (
  `N°_PROVEEDOR` int(11) NOT NULL,
  `NOMBRE_PROVEEDOR` varchar(20) DEFAULT NULL,
  `E-MAIL` varchar(30) DEFAULT NULL,
  `LOCALIDAD` varchar(20) DEFAULT NULL,
  `CALLE` varchar(30) DEFAULT NULL,
  `NUMERO` int(11) DEFAULT NULL,st: localhost    
  PRIMARY KEY (`N°_PROVEEDOR`)
) 

--

CREATE TABLE `REQUIERE` (
  `N°_INSUMO` int(11) NOT NULL,
  `ID_PAQUETE` int(11) NOT NULL,
  `CANTIDAD` int(11) DEFAULT NULL,
  PRIMARY KEY (`N°_INSUMO`),
  KEY `REQUIERE_FK_1` (`ID_PAQUETE`),
  CONSTRAINT `REQUIERE_FK` FOREIGN KEY (`N°_INSUMO`) REFERENCES `INSUMO` (`N°_INSUMO`),
  CONSTRAINT `REQUIERE_FK_1` FOREIGN KEY (`ID_PAQUETE`) REFERENCES `PAQUETE` (`ID_PAQUETE`)
) 


CREATE TABLE `SERVICIO` (
  `N°_SERVICIO` int(11) NOT NULL,
  `TIPO_SERVICIO` varchar(30) DEFAULT NULL,
  `CI` char(8) NOT NULL,
  PRIMARY KEY (`N°_SERVICIO`),
  KEY `SERVICIO_FK` (`CI`),
  CONSTRAINT `SERVICIO_FK` FOREIGN KEY (`CI`) REFERENCES `TECNICO` (`CI`)
) 

--

CREATE TABLE `SOFTWARE` (
  `N°_INSUMO` int(11) NOT NULL,
  `TIPO_SOFTWARE` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`N°_INSUMO`),
  CONSTRAINT `SOFTWARE_FK` FOREIGN KEY (`N°_INSUMO`) REFERENCES `INSUMO` (`N°_INSUMO`)
)



CREATE TABLE `SOLICITAR` (
  `N°_SERVICIO` int(11) NOT NULL,
  `CI` char(8) NOT NULL,
  `FECHA_PRESUPUESTO` date NOT NULL,
  `FECHA_INICIO` date NOT NULL,
  `FECHA_FIN` date DEFAULT NULL,
  `CANTIDAD_HORAS` int(11) DEFAULT NULL,
  `ESTADO` varchar(20) DEFAULT NULL,
  `CAUSA` varchar(50) DEFAULT NULL,
  `PRESUPUESTO` float NOT NULL,
  PRIMARY KEY (`N°_SERVICIO`,`CI`),
  KEY `SOLICITAR_FK` (`CI`),
  CONSTRAINT `SOLICITAR_FK` FOREIGN KEY (`CI`) REFERENCES `CLIENTE` (`CI`)
) 



CREATE TABLE `TECNICO` (
  `CI` char(8) NOT NULL,
  `FECHA_INGRESO` date NOT NULL,
  PRIMARY KEY (`CI`),
  CONSTRAINT `TECNICO_FK` FOREIGN KEY (`CI`) REFERENCES `PERSONA` (`CI`)
)



CREATE TABLE `TELEFONOS_PROVEEDOR` (
  `N°_PROVEEDOR` int(11) NOT NULL,
  `TELEFONOS` char(20) NOT NULL,
  PRIMARY KEY (`N°_PROVEEDOR`,`TELEFONOS`),
  CONSTRAINT `TELEFONOS_PROVEEDOR_FK` FOREIGN KEY (`N°_PROVEEDOR`) REFERENCES `PROVEEDOR` (`N°_PROVEEDOR`)
) 



CREATE TABLE `TIENE` (
  `CI` char(8) NOT NULL,
  `ID_PERFIL` int(11) DEFAULT NULL,
  PRIMARY KEY (`CI`),
  KEY `TIENE_FK` (`ID_PERFIL`),
  CONSTRAINT `TIENE_FK` FOREIGN KEY (`ID_PERFIL`) REFERENCES `PERFIL` (`ID_PERFIL`)
) 



CREATE TABLE `Telefonos_Persona` (
  `CI` char(8) NOT NULL,
  `Telefono` char(20) NOT NULL,
  PRIMARY KEY (`CI`,`Telefono`)
)


CREATE TABLE `UTILIZA` (
  `N°_SERVICIO` int(11) NOT NULL,
  `CI` char(8) NOT NULL,
  `N°_INSUMO` int(11) NOT NULL,
  PRIMARY KEY (`N°_SERVICIO`,`CI`,`N°_INSUMO`),
  KEY `UTILIZA_FK_1` (`CI`),
  KEY `UTILIZA_FK_2` (`N°_INSUMO`),
  CONSTRAINT `UTILIZA_FK` FOREIGN KEY (`N°_SERVICIO`) REFERENCES `SERVICIO` (`N°_SERVICIO`),
  CONSTRAINT `UTILIZA_FK_1` FOREIGN KEY (`CI`) REFERENCES `TECNICO` (`CI`),
  CONSTRAINT `UTILIZA_FK_2` FOREIGN KEY (`N°_INSUMO`) REFERENCES `INSUMO` (`N°_INSUMO`)
) 



 
